services:
  - type: web
    name: fastapi-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./products_orders.db
